server:
  port: 9001
  servlet:
    context-path: /plat

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_active
      logic-delete-value: 0
      logic-not-delete-value: 1