server:
  port: 9000

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1